# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ibanfirst/v0/api.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ibanfirst/v0/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ibanfirst/v0/api.proto\x12\x0cibanfirst.v0\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n\x14\x43reatePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x0c\n\x04iban\x18\x02 \x01(\t\x12\x0b\n\x03\x62ic\x18\x03 \x01(\t\x12(\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"+\n\x15\x43reatePaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\r2f\n\nApiService\x12X\n\rCreatePayment\x12\".ibanfirst.v0.CreatePaymentRequest\x1a#.ibanfirst.v0.CreatePaymentResponseBMZKgithub.com/slashformotion/proto-course/exercices/simple_protoc/ibanfirst/v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibanfirst.v0.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/slashformotion/proto-course/exercices/simple_protoc/ibanfirst/v0'
  _globals['_CREATEPAYMENTREQUEST']._serialized_start=73
  _globals['_CREATEPAYMENTREQUEST']._serialized_end=180
  _globals['_CREATEPAYMENTRESPONSE']._serialized_start=182
  _globals['_CREATEPAYMENTRESPONSE']._serialized_end=225
  _globals['_APISERVICE']._serialized_start=227
  _globals['_APISERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
